import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

const ROOT = path.join(os.homedir(), ".pi", "agent", "prusax0");
const LONG_TERM_DIR = path.join(ROOT, "memory", "long_term");
const SHORT_TERM_DIR = path.join(ROOT, "memory", "short_term");
const MAX_BLOCKS = Number(process.env.PI_MEMORY_RECALL_BLOCKS ?? "3");
const MAX_CHARS = Number(process.env.PI_MEMORY_RECALL_CHARS ?? "9000");

const STOPWORDS = new Set([
	"about",
	"after",
	"again",
	"also",
	"and",
	"any",
	"are",
	"but",
	"can",
	"could",
	"does",
	"for",
	"from",
	"have",
	"how",
	"into",
	"list",
	"more",
	"not",
	"now",
	"our",
	"please",
	"proceed",
	"should",
	"that",
	"the",
	"then",
	"this",
	"to",
	"use",
	"what",
	"when",
	"where",
	"with",
	"would",
	"you",
	"your",
]);

interface MemoryBlock {
	file: string;
	title: string;
	tags: string[];
	content: string;
}

function timestamp(): string {
	return new Date().toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "Z").replace("T", "_");
}

function extractKeywords(prompt: string): string[] {
	const raw = prompt
		.toLowerCase()
		.replace(/[`'"“”‘’]/g, " ")
		.match(/[a-z0-9][a-z0-9_-]{2,}/g) ?? [];
	const out: string[] = [];
	for (const token of raw) {
		if (STOPWORDS.has(token)) continue;
		if (!out.includes(token)) out.push(token);
		if (out.length >= 6) break;
	}
	return out;
}

function parseMemoryFile(filePath: string): MemoryBlock[] {
	const text = fs.readFileSync(filePath, "utf8");
	const file = path.basename(filePath);
	const blocks: MemoryBlock[] = [];
	const re = /^##\s+(.+?)\s*\n([\s\S]*?)(?=^---\s*$)/gm;
	let match: RegExpExecArray | null;
	while ((match = re.exec(text)) !== null) {
		const title = match[1].trim();
		const content = match[0].trim() + "\n---";
		const tagsLine = content.match(/^>\s*\*\*Tags\*\*:\s*(.+)$/m)?.[1] ?? "";
		const tags = tagsLine
			.split(",")
			.map((tag) => tag.trim().toLowerCase())
			.filter(Boolean);
		blocks.push({ file, title, tags, content });
	}
	return blocks;
}

function scoreBlock(block: MemoryBlock, keywords: string[]): number {
	const title = block.title.toLowerCase();
	const tags = block.tags.join(" ");
	const content = block.content.toLowerCase();
	let score = 0;
	for (const keyword of keywords) {
		if (block.tags.some((tag) => tag.includes(keyword) || keyword.includes(tag))) score += 8;
		if (title.includes(keyword)) score += 5;
		if (tags.includes(keyword)) score += 4;
		if (content.includes(keyword)) score += 1;
	}
	return score;
}

function recallMemory(prompt: string): string | undefined {
	if (process.env.PI_MEMORY_RECALL === "0") return undefined;
	if (!fs.existsSync(LONG_TERM_DIR)) return undefined;

	const keywords = extractKeywords(prompt);
	if (keywords.length === 0) return undefined;

	const files = fs
		.readdirSync(LONG_TERM_DIR)
		.filter((name) => name.endsWith(".md") && name !== "_index.md")
		.map((name) => path.join(LONG_TERM_DIR, name));

	const scored = files
		.flatMap((file) => {
			try {
				return parseMemoryFile(file);
			} catch {
				return [];
			}
		})
		.map((block) => ({ block, score: scoreBlock(block, keywords) }))
		.filter((item) => item.score > 0)
		.sort((a, b) => b.score - a.score)
		.slice(0, MAX_BLOCKS);

	if (scored.length === 0) return undefined;

	let body = scored
		.map(({ block, score }) => `### ${block.file} — ${block.title} (score ${score})\n\n${block.content}`)
		.join("\n\n");
	if (body.length > MAX_CHARS) body = `${body.slice(0, MAX_CHARS)}\n\n...[memory recall truncated]`;

	return `Relevant long-term memory was automatically recalled for keywords: ${keywords.join(", ")}\n\n${body}\n\nUse this only as prior context; verify facts against sources before concluding.`;
}

function writeCompactionCheckpoint(event: any): string | undefined {
	if (process.env.PI_MEMORY_COMPACTION_CHECKPOINT === "0") return undefined;
	const entry = event?.compactionEntry;
	if (!entry?.summary) return undefined;

	fs.mkdirSync(SHORT_TERM_DIR, { recursive: true });
	const details = entry.details ?? {};
	const readFiles = Array.isArray(details.readFiles) ? details.readFiles : [];
	const modifiedFiles = Array.isArray(details.modifiedFiles) ? details.modifiedFiles : [];
	const filePath = path.join(SHORT_TERM_DIR, `auto_compact_${timestamp()}.md`);
	const content = `# Auto Compaction Checkpoint — ${new Date().toISOString()}\n\n` +
		`> Generated by Pi memory extension from \`session_compact\`. Review via \`/save\` before promoting to long-term memory.\n\n` +
		`## Compaction Summary\n\n${entry.summary}\n\n` +
		`## Files Read\n\n${readFiles.length ? readFiles.map((file: string) => `- ${file}`).join("\n") : "- None recorded"}\n\n` +
		`## Files Modified\n\n${modifiedFiles.length ? modifiedFiles.map((file: string) => `- ${file}`).join("\n") : "- None recorded"}\n\n` +
		`## Promotion Guidance\n\nOnly promote completed, verified, reusable knowledge to long-term memory. Do not promote transient conversation details.\n`;
	fs.writeFileSync(filePath, content, "utf8");
	return filePath;
}

function countShortTermFiles(): number {
	if (!fs.existsSync(SHORT_TERM_DIR)) return 0;
	return fs.readdirSync(SHORT_TERM_DIR).filter((name) => name.endsWith(".md")).length;
}

export default function (pi: ExtensionAPI) {
	pi.on("before_agent_start", async (event) => {
		const memory = recallMemory(event.prompt ?? "");
		if (!memory) return;
		return { systemPrompt: `${event.systemPrompt}\n\n# Automatically Recalled Long-Term Memory\n\n${memory}` };
	});

	pi.on("session_compact", async (event, ctx) => {
		const filePath = writeCompactionCheckpoint(event);
		if (filePath && ctx.hasUI) ctx.ui.notify(`Memory checkpoint saved: ${path.basename(filePath)}`, "info");
	});

	pi.on("session_shutdown", async (_event, ctx) => {
		const count = countShortTermFiles();
		if (count > 0 && ctx.hasUI) {
			ctx.ui.notify(`${count} short-term memory file${count === 1 ? "" : "s"} pending. Run /save when ready.`, "info");
		}
	});

	pi.registerCommand("memory", {
		description: "Memory extension status. Usage: /memory [status|recall <text>]",
		handler: async (args, ctx) => {
			const trimmed = args.trim();
			if (trimmed.startsWith("recall ")) {
				const memory = recallMemory(trimmed.slice("recall ".length)) ?? "No matching long-term memory found.";
				pi.sendMessage({ customType: "memory", content: memory, display: true, details: { command: "recall" } });
				return;
			}

			const shortTermCount = countShortTermFiles();
			const longTermCount = fs.existsSync(LONG_TERM_DIR)
				? fs.readdirSync(LONG_TERM_DIR).filter((name) => name.endsWith(".md") && name !== "_index.md").length
				: 0;
			const status = [
				"Pi memory extension status",
				"",
				`- Recall hook: ${process.env.PI_MEMORY_RECALL === "0" ? "disabled" : "enabled"}`,
				`- Compaction checkpoints: ${process.env.PI_MEMORY_COMPACTION_CHECKPOINT === "0" ? "disabled" : "enabled"}`,
				`- Long-term category files: ${longTermCount}`,
				`- Pending short-term memory files: ${shortTermCount}`,
				`- Long-term path: ${LONG_TERM_DIR}`,
				`- Short-term path: ${SHORT_TERM_DIR}`,
			].join("\n");
			pi.sendMessage({ customType: "memory", content: status, display: true, details: { command: "status" } });
			if (ctx.hasUI) ctx.ui.notify("Memory status added to conversation", "info");
		},
	});
}
